# Generated by Django 3.2.7 on 2022-05-23 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check_in', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PMS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_no', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('adults', models.CharField(max_length=100)),
                ('children', models.CharField(max_length=100)),
                ('arrival_date', models.DateField()),
                ('departure_date', models.DateField()),
                ('room_type', models.CharField(max_length=100)),
                ('room_no', models.CharField(max_length=100)),
                ('comments', models.CharField(max_length=100)),
            ],
        ),
    ]
