# Generated by Django 3.2.7 on 2022-05-23 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('check_in', '0002_pms'),
    ]

    operations = [
        migrations.CreateModel(
            name='Check_In_Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_no', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=255)),
                ('arrival_date', models.DateField()),
                ('departure_date', models.DateField()),
                ('room_type', models.CharField(max_length=100)),
                ('room_no', models.CharField(max_length=100)),
                ('selfie_image', models.ImageField(upload_to='')),
                ('submit_date_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='PMS',
        ),
        migrations.AlterField(
            model_name='check_in',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='check_in',
            name='submit_date_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AddField(
            model_name='check_in_guest',
            name='check_in',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='check_in.check_in'),
        ),
    ]
