# Generated by Django 3.2.7 on 2022-05-27 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('check_in', '0003_auto_20220523_1320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='check_in_guest',
            name='check_in',
        ),
        migrations.DeleteModel(
            name='Check_In',
        ),
        migrations.DeleteModel(
            name='Check_In_Guest',
        ),
    ]
