"""
Django settings for StayMe project.

Generated by 'django-admin startproject' using Django 3.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure--#hnp*_qxuq6ft@-)7(+sf3)@lxj4%q=6h5(y^0*h%4iaayz7c'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    
    'rest_framework',
    'core',
    'check_in',
    'registration',
    'widget_tweaks',
    'compressor',
    'django_user_agents',
    'django_countries',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django_user_agents.middleware.UserAgentMiddleware',
]

ROOT_URLCONF = 'StayMe.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR / 'templates'
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'StayMe.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


#DATABASES = {
#    'default': {
#        'ENGINE': 'django.db.backends.mysql',
#        'NAME': 'StayMe',
#        'HOST': 'localhost',
#        'USER': 'root',
#        'PASSWORD': 'asdf1234'
#    }
#}


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

TIME_ZONE = 'Asia/Singapore'

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_TZ = True

# Static files finders for django-compressor
# https://django-compressor.readthedocs.io/en/stable/quickstart/#installation

STATICFILES_FINDERS = (
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
    'compressor.finders.CompressorFinder',
)


# Compressor settings for css file. JS file is compressed by default
# https://django-compressor.readthedocs.io/en/stable/settings/#django.conf.settings.COMPRESS_CSS_FILTERS

COMPRESS_ENABLED = True

COMPRESS_CSS_FILTERS = [
    'compressor.filters.css_default.CssAbsoluteFilter',
    'compressor.filters.cssmin.CSSCompressorFilter',
]

#STATIC_ROOT = BASE_DIR / 'static/'
STATIC_URL = '/static/'

COMPRESS_ROOT = BASE_DIR / 'static/'
STATICFILES_DIRS = [
     BASE_DIR / 'static/',
]

# SASS complier for django_libsass
# https://github.com/torchbox/django-libsass

COMPRESS_PRECOMPILERS = (
    ('text/x-scss', 'django_libsass.SassCompiler'),
)


# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

DATE_INPUT_FORMATS  = ['%Y-%m-%d']

SESSION_SAVE_EVERY_REQUEST = True


# Guest Facing
HOTEL_PROPERTIES = [
    {
        'id': '1',
        'name': 'Hotel A',
        'description': 'Hotel A',
        'image': '/static/img/property/1.jpg',
        'address': '1 East Street, Singapore',
    },
    {
        'id': '2',
        'name': 'Hotel B',
        'description': 'Hotel B',
        'image': '/static/img/property/2.jpg',
        'address': '1 South Road, Singapore',
    },
    {
        'id': '3',
        'name': 'Hotel C',
        'description': 'Hotel C',
        'image': '/static/img/property/3.jpg',
        'address': '1 West Avenue, Singapore',
    },
]

# OCR Endpoint configuration
OCR_ENDPOINT_URL                = 'https://cv2.gtriip.com/recognition/'
OCR_ENDPOINT_KEY                = 'nuwZUgOW.hfaXzwJh38dQHcz3g1SwLaQGdEIyOzkz'
OCR_ENDPOINT_TIMEOUT_LIMIT      = 60


# FR Endpoint configuration
FR_ENDPOINT_URL = 'https://api-us.faceplusplus.com/facepp/v3/compare'
FR_API_KEY = '17Co_wJGCGQHPHlYKMRfS83aZpvr1vxi'
FR_API_SECRET = 'aWgH63kvdi6GDULF7MEuER_sG3extGmZ'


# Encrypt and decrypt key using cryptography lib
# https://pypi.org/project/cryptography/

FERNET_KEY = b'aJAwfZCJTITCVp-76x9_z8aaFSAFvlrOIFRQEDLm6p8='

# link to access static images, configured on webserver
STATIC_IMAGE_URL    = '/static/img'
# default django variable for date format
DATE_INPUT_FORMATS  = ['%Y-%m-%d']
# set session to be saved everytime
SESSION_SAVE_EVERY_REQUEST = True
# prefix to all urls, example: on Docker use `guest/`
URL_PREFIX          = ''
TNC_LINK            = ''
PRIVACY_LINK        = ''

# check-in and registration views that use `parameter_required` validation
CHECK_IN_PARAMETER_REQUIRED_PAGES = [
    'check_in.reservation',
    'registration.guest_list',
    'registration.preference',
    'registration.other_info',
    'check_in.preauth',
    'check_in.fr',
]

